replicaCount: 1
image:
  repository: 836079437595.dkr.ecr.us-east-1.amazonaws.com/ida
  tag: persona-connectivity-probe
  pullPolicy: Always
nameOverride: ''
fullnameOverride: persona-connectivity-probe
serviceAccount:
  create: false
  name: audience-manager-service
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
env:
  PERSONA_SERVICE_URL: http://miq-persona-service-integration.ida-integration.svc
  PROBE_INTERVAL_SECONDS: '300'
  PROBE_HTTP_TIMEOUT_SECONDS: '300'
  PERSONA_API_PREFIX: audience-query/api
istio:
  enabled: false
